## ----- Settings ------ ##
plugin-preifx: '&6[Levels] '
start-level: 1
## ----- MySQL Settings ----- ##
MySQL:
  use: false
  host: 'localhost'
  port: 3306
  database: 'bukkit'
  username: 'root'
  password: ''
